import type { LegacyGroup } from './types'

const group: LegacyGroup = {
  id: 'Custom',
  label: 'Custom',
  packs: [
    { kind: 'pack', label:'Misc. Custom Frames', id:'MiscCustom' },
    { kind: 'pack', label:'Deck Covers', id:'CustomDeckCover' },
    { kind: 'pack', label:'Simple Inventions', id:'SimpleInventions' },
    { kind: 'pack', label:'Tapped (Horizontal M15)', id:'Tapped' },
    { kind: 'pack', label:'Textless Duals', id:'CustomDualLands' },
    { kind: 'pack', label:'Textless Seventh', id:'SeventhTextless' },
    { kind: 'pack', label:'Seventh Edition Planeswalkers', id:'PlaneswalkerSeventh' },
    { kind: 'pack', label:'Seventh Edition Sagas', id:'OldSaga' },
    { kind: 'pack', label:'Seventh Edition Snow Lands', id:'SeventhSnowLands' },
    { kind: 'pack', label:'Floating Old Border', id:'OldFloating' },
    { kind: 'pack', label:'Floating Old Border (Short)', id:'OldFloatingShort' },
    { kind: 'pack', label:'Burning Revelation (SLD)', id:'BurningRevelation' },

    { kind: 'label', label: 'Modern M15 Eighth Edition Style' },
    { kind: 'pack', label:'Regular', id:'M15Eighth' },
    { kind: 'pack', label:'Nyx', id:'M15EighthNyx' },
    { kind: 'pack', label:'Snow', id:'M15EighthSnow' },
    { kind: 'pack', label:'Universes Beyond', id:'M15EighthUB' },

    { kind: 'label', label: 'Modern M15 Eighth Edition Transform' },
    { kind: 'pack', label:'Regular (Front)', id:'M15EighthTransformFront' },
    { kind: 'pack', label:'Regular (Back)', id:'M15EighthTransformBack' },
    { kind: 'pack', label:'Nyx (Front)', id:'M15EighthTransformNyxFront' },
    { kind: 'pack', label:'Nyx (Back)', id:'M15EighthTransformNyxBack' },
    { kind: 'pack', label:'Snow (Front)', id:'M15EighthTransformSnowFront' },
    { kind: 'pack', label:'Snow (Back)', id:'M15EighthTransformSnowBack' },
    { kind: 'pack', label:'Universes Beyond (Front)', id:'M15EighthTransformUBFront' },
    { kind: 'pack', label:'Universes Beyond (Back)', id:'M15EighthTransformUBBack' },

    { kind: 'label', label: 'Modern M15 Eighth MDFC' },
    { kind: 'pack', label:'Regular (MDFC)', id:'M15EighthModal' },
    { kind: 'pack', label:'Nyx (MDFC)', id:'M15EighthModalNyx' },
    { kind: 'pack', label:'Snow (MDFC)', id:'M15EighthModalSnow' },
    { kind: 'pack', label:'Universes Beyond (MDFC) ', id:'M15EighthModalUB' },

    { kind: 'label', label: 'Modern M15 Eighth Edition Tokens' },
    { kind: 'pack', label:'Regular', id:'M15EighthToken' },
    { kind: 'pack', label:'Nyx', id:'M15EighthNyxToken' },
    { kind: 'pack', label:'Snow', id:'M15EighthSnowToken' },
    { kind: 'pack', label:'Universes Beyond', id:'M15EighthUBToken' },

    { kind: 'label', label: 'Modern M15 Eighth Edition Tokens (Textless)' },
    { kind: 'pack', label:'Regular (Textless)', id:'M15EighthTokenTextless' },
    { kind: 'pack', label:'Nyx (Textless)', id:'M15EighthNyxTokenTextless' },
    { kind: 'pack', label:'Snow (Textless)', id:'M15EighthSnowTokenTextless' },
    { kind: 'pack', label:'Universes Beyond (Textless)', id:'M15EighthUBTokenTextless' },

    { kind: 'label', label: 'Classicshifted Series' },
    { kind: 'pack', label:'Classicshifted', id:'Classicshifted' },
    { kind: 'pack', label:'Classicshifted Nickname', id:'ClassicshiftedNickname' },
    { kind: 'pack', label:'Classicshifted Lands', id:'ClassicshiftedLands' },
    { kind: 'pack', label:'Classicshifted Planeswalkers', id:'ClassicshiftedPlaneswalker' },
    { kind: 'pack', label:'Classicshifted Planeswalker Transform Addons', id:'ClassicshiftedPlaneswalkerTransform' },
    { kind: 'pack', label:'Classicshifted Sagas', id:'ClassicshiftedSaga' },
    { kind: 'pack', label:'Classicshifted MDFC Addons', id:'ClassicshiftedDFC' },
    { kind: 'pack', label:'Classicshifted Transform Addons', id:'ClassicshiftedTransform' },
    { kind: 'pack', label:'Color Identity Pips', id:'ClassicshiftedCIPips' },

    { kind: 'label', label: 'StoneCutter Series by Smaug' },
    { kind: 'pack', label:'StoneCutter', id:'StoneCutterDeluxe' },
    { kind: 'pack', label:'StoneCutter Nickname Addons', id:'StoneCutterDeluxeNicknameAddons' },
    { kind: 'pack', label:'StoneCutter Extended Art', id:'StoneCutterDeluxeExtended' },
    { kind: 'pack', label:'StoneCutter Planeswalker', id:'StoneCutterDeluxePlaneswalker' },
    { kind: 'pack', label:'StoneCutter Planeswalker Extended Art', id:'StoneCutterDeluxePlaneswalkerExtended' },
    { kind: 'pack', label:'StoneCutter Planeswalker Transform Addons', id:'StoneCutterDeluxePlaneswalkerTransformAddons' },
    { kind: 'pack', label:'StoneCutter Saga', id:'StoneCutterDeluxeSaga' },
    { kind: 'pack', label:'StoneCutter Class(y)', id:'StoneCutterDeluxeClass' },
    { kind: 'pack', label:'StoneCutter Case', id:'StoneCutterDeluxeCase' },
    { kind: 'pack', label:'StoneCutter MDFC Addons', id:'StoneCutterDeluxeDFC' },
    { kind: 'pack', label:'StoneCutter Transform Addons', id:'StoneCutterDeluxeTransformAddons' },

    { kind: 'label', label: 'Showcase Frame Varients' },
    { kind: 'pack', label:'Short Neon (NEO)', id:'NEONeonShort' },
    { kind: 'pack', label:'Colored Golden Age (SNC)', id:'SNCGildedColored' },
    { kind: 'pack', label:'Textless Golden Age (SNC)', id:'SNCGildedTextless' },
    { kind: 'pack', label:'Textless Equinox (MID)', id:'EquinoxTextless' },
    { kind: 'pack', label:'Horizontal Japanese Mystical Archive (STA)', id:'MysticalArchiveJPHorizontal' },
    { kind: 'pack', label:'Extended Art Invocations', id:'AKHInvocationExtended' },
    { kind: 'pack', label:'Textless Inventions', id:'TextlessInvention' },

    { kind: 'label', label: 'Custom Addons' },
    { kind: 'pack', label:'Brawl Legend Crowns', id:'Brawl' },

    { kind: 'label', label: 'Custom Community Frames' },
    { kind: 'pack', label:'Cartoony - Sheepwave', id:'Cartoony' },
    { kind: 'pack', label:'Neon - Elry', id:'CustomNeon' },
    { kind: 'pack', label:'Ixalan - @feuer_ameise', id:'FeuerAmeiseIxalan' },
    { kind: 'pack', label:'Kaldheim, Fullart - @feuer_ameise', id:'FeuerAmeiseKaldheim' },
    { kind: 'pack', label:'Celid\'s Asap', id:'CustomCelidAsap' },
    { kind: 'pack', label:'Magrao\'s Kaldheim', id:'CustomMagraoKaldheim' },
    { kind: 'pack', label:'Pokemon', id:'Pokemon' },
    { kind: 'pack', label:'Circuit', id:'Circuit' }
  ],
}

export default group
