import type { LegacyGroup } from './types'

const group: LegacyGroup = {
  id: 'Showcase-5',
  label: 'Showcase Frames',
  packs: [
    { kind: 'label', label: 'Set Showcase Frames (Chronological)' },
    { kind: 'pack', label: 'Avatar Elemental (TLA)', id:'Elemental' },
    { kind: 'pack', label: 'Borderless Stellar Sights (EOS)', id:'BorderlessStellarSights' },
    { kind: 'pack', label: 'Borderless Source Material', id:'FCA' },
    { kind: 'pack', label: 'Draconic (TDM)', id:'Draconic' },
    { kind: 'pack', label: 'Ghostfire (TDM)', id:'Ghostfire' },
    { kind: 'pack', label: 'Japan Showcase', id:'JapanShowcase' },
    { kind: 'pack', label: 'Paranormal (DSK)', id:'Paranormal' },
    { kind: 'pack', label: 'Bloomburrow Borderless (BLB)', id:'BloomburrowBorderless' },
    { kind: 'pack', label: 'Woodland (BLB)', id:'Woodland' },
    { kind: 'pack', label: 'Memory Corridor (ACR)', id:'MemoryCorridor' },
    { kind: 'pack', label: 'Breaking News (OTP)', id:'BreakingNews' },
    { kind: 'pack', label: 'Vault (BIG)', id:'Vault' },
    { kind: 'pack', label: 'Wanted Poster (OTJ)', id:'Wanted' },
    { kind: 'pack', label: 'Pip-Boy (PIP)', id:'Pipboy' },
    { kind: 'pack', label: 'Dossier (MKM)', id:'Dossier' },
    { kind: 'pack', label: 'Legends of Ixalan - Pattern 1 (LCI)', id:'IxalanLegends1' },
    { kind: 'pack', label: 'Legends of Ixalan - Pattern 2 (LCI)', id:'IxalanLegends2' },
    { kind: 'pack', label: 'Legends of Ixalan - Pattern 3 (LCI)', id:'IxalanLegends3' },
    { kind: 'pack', label: 'Scrolls of Middle-earth (LTR)', id:'Scroll' },
    { kind: 'pack', label: 'Enchanting Tales (WOT)', id:'EnchantingTales' },
    { kind: 'pack', label: 'Eldraine Storybooks: Adventures (WOE)', id:'StorybookWOE' },
    { kind: 'pack', label: 'TARDIS (WHO)', id:'TARDIS' },
    { kind: 'pack', label: 'Ring (LTR)', id:'Ring' },
    { kind: 'pack', label: 'Eldraine Storybooks (MOM)', id:'StorybookMUL' },
    { kind: 'pack', label: 'Ixalan Coin (MOM)', id:'IxalanCoin' },
    { kind: 'pack', label: 'Tarkir Sketch (MOM)', id:'Tarkir' },
    { kind: 'pack', label: 'Ikoria Crystal (MOM)', id:'Crystal' },
    { kind: 'pack', label: 'Ravnica City (MOM)', id:'Ravnica' },
    { kind: 'pack', label: 'Oil Slick (ONE)', id:'OilSlick' },
    { kind: 'pack', label: 'Shattered Glass (BOT)', id:'ShatteredGlass' },
    { kind: 'pack', label: 'Stained Glass (DMU)', id:'DMUStainedGlass' },
    { kind: 'pack', label: 'Golden Age (SNC)', id:'SNCGilded' },
    { kind: 'pack', label: 'Art Deco (SNC)', id:'SNCArtDeco' },
    { kind: 'pack', label: 'Skyscraper (SNC)', id:'SNCSkyscraper' },
    { kind: 'pack', label: 'Ninja (NEO)', id:'NeoNinja' },
    { kind: 'pack', label: 'Samurai (NEO)', id:'NeoSamurai' },
    { kind: 'pack', label: 'Neon (NEO)', id:'NeoNeon' },
    { kind: 'pack', label: 'Double Feature (DBL)', id:'DoubleFeature' },
    { kind: 'pack', label: 'Double Feature: Transform (DBL)', id:'DoubleFeatureTransform' },
    { kind: 'pack', label: 'Fang (VOW)', id:'Fang' },
    { kind: 'pack', label: 'Equinox: Single-faced (MID)', id:'Equinox' },
    { kind: 'pack', label: 'Equinox: Transform Front (MID)', id:'EquinoxFront' },
    { kind: 'pack', label: 'Equinox: Transform Back (MID)', id:'EquinoxBack' },
    { kind: 'pack', label: 'Eternal Night (MID)', id:'EternalNight' },
    { kind: 'pack', label: 'D&D Sourcebook (AFR)', id:'DNDSourcebook' },
    { kind: 'pack', label: 'D&D Module (AFR)', id:'DNDModule' },
    { kind: 'pack', label: 'Sketch Cards (MH2)', id:'MH2' },
    { kind: 'pack', label: 'Mystical Archive (STA)', id:'MysticalArchive' },
    { kind: 'pack', label: 'Japanese Mystical Archive (STA)', id:'MysticalArchiveJP' },
    { kind: 'pack', label: 'Horizontal Japanese Mystical Archive (STA)', id:'MysticalArchiveJPHorizontal' },
    { kind: 'pack', label: 'Kaldheim (KHM)', id:'Kaldheim-2' },
    { kind: 'pack', label: 'Nonlegendary Kaldheim (KHM)', id:'KaldheimNonleg' },
    { kind: 'pack', label: 'Commander Legends (CMR)', id:'CommanderLegends' },
    { kind: 'pack', label: 'Zendikar Rising (ZNR)', id:'ZendikarRising' },
    { kind: 'pack', label: 'M21 Signature Spellbooks (M21)', id:'M21' },
    { kind: 'pack', label: 'Theros Beyond Death (THB)', id:'M15NyxShowcase' },
    { kind: 'pack', label: 'Eldraine Storybooks: Adventures (ELD)', id:'Storybook' },

    { kind: 'label', label: 'Generic Showcase Frames' },
    { kind: 'pack', label: 'Borderless', id:'GenericShowcase' },
    { kind: 'pack', label: 'Borderless (Alt)', id:'Borderless' },
    { kind: 'pack', label: 'Fullart', id:'M15ClearTextboxes' },
    { kind: 'pack', label: 'Nickname ("Godzilla")', id:'M15Nickname' },
    { kind: 'pack', label: 'Extended Art (Regular)', id:'M15BoxTopper' },
    { kind: 'pack', label: 'Extended Art (Shorter Textbox)', id:'M15ExtendedArtShort' },
    { kind: 'pack', label: 'FNM Promo (Inverted Promos)', id:'FNM' },
    { kind: 'pack', label: 'Full Text', id:'FullText' },
    { kind: 'pack', label: 'Full Text (Alt)', id:'FullTextAlt' },
    { kind: 'pack', label: 'Foil-Etched', id:'disabled' },
    { kind: 'pack', label: 'Etched', id:'Etched' },
    { kind: 'pack', label: 'Etched (Nyx)', id:'EtchedNyx' },
    { kind: 'pack', label: 'Etched (Snow)', id:'EtchedSnow' },
    { kind: 'pack', label: 'Legend Crowns (Etched)', id:'LegendCrownsEtched' },
    { kind: 'pack', label: 'Inner Crowns (Etched)', id:'InnerCrownsEtched' },

    { kind: 'label', label: 'Universes Beyond' },
    { kind: 'pack', label: 'Universes Beyond', id:'UB' },
    { kind: 'pack', label: 'Universes Beyond (Full art)', id:'UBFull' },
    { kind: 'pack', label: 'Universes Beyond (Extended art)', id:'UBExtendedArt' },
    { kind: 'pack', label: 'Legend Crowns (Universes Beyond)', id:'UBLegendCrowns' },
    { kind: 'pack', label: 'Floating Legend Crowns (Universes Beyond)', id:'UBLegendCrownsFloating' },

    { kind: 'label', label: 'Masterpieces/Other' },
    { kind: 'pack', label: 'Phyrexian', id:'Praetors' },
    { kind: 'pack', label: 'ZNR Expeditions (2020)', id:'ExpeditionZNR-1' },
    { kind: 'pack', label: 'Signature Spellbook (Jace/Gideon)', id:'SignatureSpellbook' },
    { kind: 'pack', label: 'Ixalan Maps', id:'Ixalan' },
    { kind: 'pack', label: 'Amonkhet Invocations (u/Smyris)', id:'Invocation' },
    { kind: 'pack', label: 'Amonkhet Invocations (Multiverse Legends)', id:'InvocationMUL' },
    { kind: 'pack', label: 'Kaladesh Inventions', id:'Invention' },
    { kind: 'pack', label: 'BFZ Expeditions (2015)', id:'ExpeditionBFZ-1' },
    { kind: 'pack', label: 'SDCC15 (Blackout)', id:'SDCC15' },
    { kind: 'pack', label: 'Future Shifted', id:'FutureRegular' },

    { kind: 'label', label: 'Addons' },
    { kind: 'pack', label: 'Legend Crowns', id:'M15LegendCrowns' },
    { kind: 'pack', label: 'Legend Crowns (Universes Beyond)', id:'UBLegendCrowns' },
    { kind: 'pack', label: 'Floating Legend Crowns', id:'M15LegendCrownsFloating' },
    { kind: 'pack', label: 'Floating Legend Crowns (Universes Beyond)', id:'UBLegendCrownsFloating' },
    { kind: 'pack', label: 'Inner Crowns', id:'M15InnerCrowns' },
    { kind: 'pack', label: 'Nicknames', id:'M15Nickname-2' },
    { kind: 'pack', label: 'Smooth Nickname Legend Crowns', id:'M15SmoothNickname' },
    { kind: 'pack', label: 'Japan Showcase Nicknames', id:'JapanShowcaseNicknames' },
    { kind: 'pack', label: 'Holo Stamps', id:'M15HoloStamps' },
    { kind: 'pack', label: 'Dark Power/Toughness', id:'M15DarkPT' },
    { kind: 'pack', label: 'Colored Borders', id:'M15Borders' },
    { kind: 'pack', label: 'Color Identity Pips', id:'M15CIPips' },
    { kind: 'pack', label: '"The List" Stamp', id:'TheList' },

    { kind: 'label', label: 'Custom Addons' },
    { kind: 'pack', label: 'Brawl Legend Crowns', id:'Brawl' }
  ],
}

export default group
